const { Artist } = require('../models');

const artistData = [
   {artist_id: "1", artist_name: "Battle Front", popularity_index: 1, description: "Harmonious melodies entwine with pulsating rhythms, igniting passions and emotions within the soul of listeners worldwide."},
   {artist_id: "2", artist_name: "Motor", popularity_index: 1, description: "Vibrant harmonies cascade through the air, intertwining with electrifying beats and soulful lyrics, captivating audiences far and wide."},
   {artist_id: "3", artist_name: "The Fine Print", popularity_index: 1.2, description: "Eclectic sounds blend seamlessly, weaving intricate tapestries of sonic exploration, resonating with the hearts and minds of devoted fans."},
   {artist_id: "4", artist_name: "Death Gary", popularity_index: 1, description: "Dynamic arrangements ebb and flow, evoking a myriad of emotions, from euphoria to introspection, as the music transcends boundaries."},
   {artist_id: "5", artist_name: "Mix29", popularity_index: 1, description: "Energetic performances electrify the stage, fueling the fervor of fans who dance and sing along to every infectious chorus."},
   {artist_id: "6", artist_name: "Blind Luck", popularity_index: 1.4, description: "Expressive vocals soar over thunderous drums and soaring guitars, delivering anthems of hope and defiance to an eager audience."},
   {artist_id: "7", artist_name: "No No Chuck", popularity_index: 1, description: "Haunting melodies linger in the air, casting a spell of enchantment over listeners who are transported to distant realms of imagination."},
   {artist_id: "8", artist_name: "Holly Grisham and Mark Newsome", popularity_index: 1, description: "Soul-stirring ballads resonate with raw emotion, as tender lyrics tug at heartstrings, leaving a lasting impression on all who listen."},
   {artist_id: "9", artist_name: "The Mollies", popularity_index: 1, description: "Lush orchestration envelops the senses, as symphonic elements meld with rock-infused energy, creating a sonic landscape of epic proportions."},
   {artist_id: "10", artist_name: "Ain’t No Crime", popularity_index: 1, description: "Infectious grooves groove and groove, inviting listeners to move and groove, as the band grooves on stage with infectious energy."},
   {artist_id: "11", artist_name: "Bee Brandy", popularity_index: 1.6, description: "Psychedelic sounds swirl and swirl, hypnotizing the audience with their mesmerizing rhythms and kaleidoscopic textures."},
   {artist_id: "12", artist_name: "Arkansauce", popularity_index: 1, description: "Atmospheric melodies drift and swirl, enveloping the listener in a dreamlike haze of sound and sensation."},
   {artist_id: "13", artist_name: "Katydidn’t", popularity_index: 1, description: "Funky basslines thump and throb, driving the music forward with irresistible energy and groove."},
   {artist_id: "14", artist_name: "Don’t Call Johnny", popularity_index: 1, description: "Soulful vocals soar and soar, reaching new heights of emotion and expression with each heartfelt lyric."},
   {artist_id: "15", artist_name: "ParmaQueen", popularity_index: 3, description: "Dynamic guitar solos shred and shred, electrifying the crowd with their lightning-fast licks and fiery passion."},
   {artist_id: "16", artist_name: "Astor Jimenez", popularity_index: 1, description: "Jazz-infused rhythms swing and sway, transporting listeners to smoky clubs and dimly lit bars of yesteryear."},
   {artist_id: "17", artist_name: "Dayzer", popularity_index: 1, description: "Reggae beats pulse and pulse, infusing the music with an infectious sense of rhythm and groove."},
   {artist_id: "18", artist_name: "Not My Day Job", popularity_index: 1, description: "Bluesy melodies wail and moan, echoing the pain and longing of the human experience with raw honesty."},
   {artist_id: "19", artist_name: "Koala Stomper", popularity_index: 1, description: "Ambient textures shimmer and shimmer, creating a ethereal soundscape that transports the listener to otherworldly realms."},
   {artist_id: "20", artist_name: "Railroaded", popularity_index: 2, description: "Country twang and twang, evoking the wide-open spaces and dusty roads of the American heartland."},
   {artist_id: "21", artist_name: "Subluxury Grifters", popularity_index: 1, description: "Baroque flourishes dance and twirl, adding a touch of elegance and sophistication to the band's eclectic sound."},
   {artist_id: "22", artist_name: "Too Far To Go", popularity_index: 1, description: "Punk rock anthems rage and rage, channeling the rebellious spirit of youth with fiery intensity and attitude."},
   {artist_id: "23", artist_name: "Drivel Machine", popularity_index: 1.4, description: "Electronic beats pulse and pulse, driving the music forward with relentless energy and futuristic flair."},
   {artist_id: "24", artist_name: "Fecal Plug", popularity_index: 1, description: "Indie-pop melodies bubble and fizz, brimming with infectious hooks and catchy choruses that stick in the mind."},
   {artist_id: "25", artist_name: "Street Kicker", popularity_index: 1, description: "Experimental sounds push the boundaries of conventional music, daring listeners to explore new sonic landscapes."},
   {artist_id: "26", artist_name: "Hollow Point", popularity_index: 1, description: "Acoustic ballads whisper and sigh, revealing the vulnerability and beauty of the human experience with delicate grace."},
   {artist_id: "27", artist_name: "Alice Cawlwell", popularity_index: 1, description: "Orchestral arrangements swell and swell, swelling with emotion and drama as they build to a breathtaking crescendo."},
   {artist_id: "28", artist_name: "HiroYuko", popularity_index: 1.2, description: "Synth-pop hooks sparkle and shine, lighting up the dance floor with their infectious energy and catchy melodies."},
   {artist_id: "29", artist_name: "Downward Dave", popularity_index: 1, description: "Grunge-inspired riffs roar and roar, unleashing a torrent of raw emotion and angst with every power chord."},
   {artist_id: "30", artist_name: "Fat Mars", popularity_index: 1, description: "Hip-hop beats bump and bump, driving the music forward with infectious energy and streetwise swagger."},
   {artist_id: "31", artist_name: "Bomb Them All", popularity_index: 1, description: "Progressive rock epics sprawl and sprawl, unfolding like musical odysseys that take the listener on a journey through time and space."},
   {artist_id: "32", artist_name: "Pastiche", popularity_index: 1, description: "Celtic melodies dance and swirl, conjuring images of misty moors and ancient forests with their haunting beauty."},
   {artist_id: "33", artist_name: "Happy Farm", popularity_index: 1, description: "Gospel-inspired harmonies soar and soar, lifting the spirit and stirring the soul with their transcendent power."},
   {artist_id: "34", artist_name: "Not To Like", popularity_index: 3, description: "Synthwave sounds pulse and pulse, evoking the neon-lit landscapes and retro-futuristic vibes of a bygone era."},
   {artist_id: "35", artist_name: "Yell The Name", popularity_index: 1, description: "Post-punk rhythms throb and throb, infusing the music with an edgy intensity and darkly atmospheric vibe."},
   {artist_id: "36", artist_name: "99% Uptime", popularity_index: 1, description: "Ska-inflected grooves skank and skank, getting the crowd moving with their infectious energy and upbeat tempo."},
   {artist_id: "37", artist_name: "Goalpost Climber", popularity_index: 1, description: "Shoegaze textures shimmer and shimmer, enveloping the listener in a swirling sea of sound and sensation."},
   {artist_id: "38", artist_name: "Undertongue", popularity_index: 1, description: "New wave anthems pulse and pulse, capturing the spirit of the '80s with their catchy hooks and synth-driven sound."},
   {artist_id: "39", artist_name: "Maddie Meeker", popularity_index: 1, description: "Surf rock riffs crash and crash, conjuring images of sun-drenched beaches and endless waves with their infectious energy."},
   {artist_id: "40", artist_name: "John", popularity_index: 1.2, description: "Power metal epics soar and soar, transporting the listener to fantastical realms of dragons and wizards with their epic scope."},
   {artist_id: "41", artist_name: "All The Pieces", popularity_index: 1, description: "Post-rock soundscapes sprawl and sprawl, unfolding like musical tapestries that ebb and flow with cinematic grandeur."},
   {artist_id: "42", artist_name: "Betrayal", popularity_index: 1, description: "Emo-pop melodies shimmer and shimmer, capturing the bittersweet beauty of adolescence with their heartfelt lyrics and catchy hooks."},
   {artist_id: "43", artist_name: "Brass Fighter", popularity_index: 1.5, description: "Noise rock cacophonies roar and roar, pushing the boundaries of sonic experimentation with their abrasive sound and confrontational attitude."},
   {artist_id: "44", artist_name: "Pert Near", popularity_index: 1, description: "Folk-punk anthems rage and rage, channeling the spirit of rebellion and protest with their raw energy and DIY ethos."},
   {artist_id: "45", artist_name: "Smile Milo", popularity_index: 1, description: "Industrial beats throb and throb, pulsating with mechanical precision and dystopian atmosphere."},
   {artist_id: "46", artist_name: "Grapes of Ruth", popularity_index: 1, description: "Trip-hop grooves pulse and pulse, blending elements of hip-hop, electronica, and ambient music into a hypnotic sonic collage."},
   {artist_id: "47", artist_name: "Luna Tick", popularity_index: 2, description: "Math rock complexities twist and turn, challenging the listener with their intricate rhythms and unconventional song structures."},
   {artist_id: "48", artist_name: "Not My Problem", popularity_index: 2, description: "Ambient jazz textures swirl and swirl, creating a dreamlike atmosphere that evokes the smoky clubs and dimly lit alleys of a noir film."},
   {artist_id: "49", artist_name: "Serving Space", popularity_index: 1, description: "Nu-metal anthems rage and rage, channeling the angst and aggression of a generation with their crushing riffs and primal energy."},
   {artist_id: "50", artist_name: "Quarter Spinner", popularity_index: 1, description: "Glam rock extravaganzas shimmer and shine, capturing the spirit"},
];

const seedArtist = () => Artist.bulkCreate(artistData);

module.exports = seedArtist;


