const { TaxRate } = require('../models');

const taxData= 
[
   {state: "AL", rate: 0.08},
   {state: "AK", rate: 0.06},
   {state: "AZ", rate: 0.09},
   {state: "AR", rate: 0.07},
   {state: "CA", rate: 0.03},
   {state: "CO", rate: 0.05},
   {state: "CT", rate: 0.02},
   {state: "DE", rate: 0.10},
   {state: "FL", rate: 0.04},
   {state: "GA", rate: 0.01},
   {state: "HI", rate: 0.09},
   {state: "ID", rate: 0.07},
   {state: "IL", rate: 0.08},
   {state: "IN", rate: 0.06},
   {state: "IA", rate: 0.03},
   {state: "KS", rate: 0.02},
   {state: "KY", rate: 0.10},
   {state: "LA", rate: 0.04},
   {state: "ME", rate: 0.05},
   {state: "MD", rate: 0.08},
   {state: "MA", rate: 0.06},
   {state: "MI", rate: 0.09},
   {state: "MN", rate: 0.01},
   {state: "MS", rate: 0.10},
   {state: "MO", rate: 0.07},
   {state: "MT", rate: 0.02},
   {state: "NE", rate: 0.03},
   {state: "NV", rate: 0.08},
   {state: "NH", rate: 0.05},
   {state: "NJ", rate: 0.04},
   {state: "NM", rate: 0.06},
   {state: "NY", rate: 0.09},
   {state: "NC", rate: 0.01},
   {state: "ND", rate: 0.07},
   {state: "OH", rate: 0.10},
   {state: "OK", rate: 0.08},
   {state: "OR", rate: 0.06},
   {state: "PA", rate: 0.04},
   {state: "RI", rate: 0.03},
   {state: "SC", rate: 0.02},
   {state: "SD", rate: 0.05},
   {state: "TN", rate: 0.09},
   {state: "TX", rate: 0.01},
   {state: "UT", rate: 0.10},
   {state: "VT", rate: 0.07},
   {state: "VA", rate: 0.08},
   {state: "WA", rate: 0.06},
   {state: "WV", rate: 0.09},
   {state: "WI", rate: 0.04},
   {state: "WY", rate: 0.03},
 ];
 
 const seedTaxes = () => TaxRate.bulkCreate(taxData);

 module.exports = seedTaxes;